import { Knex } from 'knex';

import { ETableNames } from '../ETableNames';

export const seed = async (knex: Knex) => {
  const [{ count }] = await knex(ETableNames.cidade).count<[{ count: number }]>(
    '* as count'
  );
  if (!Number.isInteger(count) || Number(count) > 0) return;

  const cidadesToInsert = municipioAngola.map((nomeDaCidade) => ({
    nome: nomeDaCidade,
  }));
  await knex(ETableNames.cidade).insert(cidadesToInsert);
};
const municipioAngola = [
  'Luanda',
  'Viana',
  'Cacuaco',
  'Cacuaco',
  'Cacuaco',
  'Cacuaco',
  'Cacuaco',
  'Cacuaco',
  'Cacuaco',
  'Belas',
  'Cazenga',
  'Lubango',
  'Huambo',
  'Matala',
  'Cabinda',
  'Benguela ',
  'Uíge',
  'Malanje',
  'Cuíto',
  'Saurimo',
  'Talatona',
  'Lobito',
  'Caála',
  'Menongue',
  'Moçâmedes ',
  'Andulo',
  'Sumbe',
  'Chinguar',
  'Camacupa',
  'Cubal ',
  'Soyo',
  'Caluquembe	     ',
  'Amboim	         ',
  'Porto Amboim	   ',
  'Catabola	       ',
  'Ganda	          ',
  'Dande	          ',
  'Cuanhama	       ',
  'Mabanza Congo	  ',
  'Seles',
  'Caconda ',
  'Moxico',
  'Catumbela',
  'Cazengo ',
  'Quibala',
  '-Muteba',
  'Londuimbale',
  'Quipungo',
  'Bocoio',
  'Namacunde	      ',
  'Chiange	        ',
  'Ombadja	        ',
  'Muconda	        ',
  'Cela	           ',
  'Chibia	         ',
  'Caxito	         ',
  'Negage	         ',
  'Cacula	         ',
  'Quimbele	       ',
  'Damba	          ',
  'Ebo	            ',
  'Maquela do Zombo',
  'Cuemba	         ',
  'Ícolo e Bengo	  ',
  'Nharea	         ',
  'Gabela	         ',
  'Libolo	         ',
  'Ambaca	         ',
  'Quilengues	     ',
  'Virei	          ',
  'Cassongue	      ',
  'Chicomba	       ',
  'Chitato	        ',
  'Jamba	          ',
  'Alto Cauale	    ',
  'Baía Farta	     ',
  'Cacuso	         ',
  'Dala	           ',
  'Humpata	        ',
  'Balombo	        ',
  'Samba Caju	     ',
  'Cambambe	       ',
  'Ekunha	         ',
  'Longonjo	       ',
  'Calai	          ',
  'Lucapa	         ',
  'Mussende	       ',
  'Ecunha	         ',
  'Chongorói	      ',
  'Caimbambo	      ',
  'Quela	          ',
  '-Camulemba	     ',
  'Conda	          ',
  'Quilenda	       ',
  'Buengas	        ',
  'Cambulo	        ',
  'Cacolo	         ',
  'Calandula	      ',
  'Cahama	         ',
  'Ucuma	          ',
  '-Tcholoanga	    ',
  'Golungo Alto	   ',
  'Cuimba	         ',
  'Cunhinga	       ',
  'Chitembo	       ',
  'Cuito Cuanavale	',
  'Catchiungo	     ',
  'Caungula	       ',
  'Cuango	         ',
  'Sanza Pombo	    ',
  'Nambuangongo	   ',
  '-Catembo	       ',
  'Cuvango	        ',
  'Bibala	         ',
  'Bailundo	       ',
  'Curoca	         ',
  'Tômbua	         ',
  'Ucuma	          ',
  'Caombo	         ',
  'Bembe ',
  'Cuvelai',
  'Zeto',
  'Camucuio',
  'Quissama',
  'Bungo',
  'Mucaba',
  'Cuchi',
  'Lucala',
  'Massango',
  'Dirico',
  '-Zau	',
  'Tomboco',
  'Cameia',
  'Bundas',
  'Lubalo',
  'Puri',
  'Gonguembo',
  'Quirima',
  'Rivungo',
  'Chipindo',
  'Quitexe',
  'Luquembo',
  'Cangandala',
  'Luau',
  'Marimba',
  '-Dia-Baze',
  'Camucuio',
  'Léua	',
  'Mavinga',
  'Mungo',
  'Dembos',
  'Mucari ',
  'Noqui',
  'Luchazes',
  'Banga ',
  'Ambriz',
  'Luacano',
  'Cuilo',
  'Cacongo',
  'Alto Zambeze',
  'Cuangar',
  'Camanongue',
  'Belize',
  'Zombo ',
  'Ambuíla',
  'Bula Atumba',
  'Cuaba Nzogo',
  'Macocola',
  'Songo',
  'Malanje',
  'Bolongongo',
  'Quiculungo',
  'Tchindjenje',
  'Pango Aluquém',
  'Nancova',
  'Longa',
];
